jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag heritrix:$(date +%s)
      working-directory: docker
name: Docker Image CI
on:
  repository_dispatch:
    types: trigger-ga___docker-image.yml
